name: Merge upstream
on:
  issues:
    types: [opened, reopened, edited]

jobs:
  merge_upstream:
    name: Create merge upstream PR
    if: startsWith(github.event.issue.title, 'Merge upstream')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/ros/rosdistro.git
          git fetch upstream
      - name: Create upstream merge branch
        run: |
          git config --global user.email 'github-actions[bot]'
          git config --global user.name '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b merge-upstream-$(date '+%Y-%m-%d')
          git merge --no-ff --no-edit upstream/master
      - name: Remove upstream remote
        run: git remote remove upstream # avoid to open PR in upstream repo
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: alpine-custom-apk
          pr_title: Merge upstream
          pr_body: "close #${{ github.event.issue.number }}"
